yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
    path('justpage/', views.JustStaticPage.as_view(), name='justpage')
]

yatube/posts/urls.py
from django.urls import path

from posts import views


app_name = 'posts'


urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()
OGR_TEXT = 15


class Group(models.Model):
    title = models.CharField(max_length=200,
                             unique=True,
                             verbose_name='title')
    slug = models.SlugField(unique=True, verbose_name='slug')
    description = models.TextField(verbose_name='description')

    def __str__(self) -> str:
        return self.title


class Comment(models.Model):
    pass


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text[:OGR_TEXT]

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        labels = {
            'group': 'группа',
            'text': 'пост',
        }
        fields = ('text', 'group')


class CommentForm(forms.ModelForm):
    pass

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .utilities import get_paginator
from .models import Group, Post, User
from .forms import PostForm, CommentForm

LIMIT_POSTS = 10


def index(request):
    posts = Post.objects.select_related('group', 'author').all()
    page_obj = get_paginator(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = get_paginator(request, posts)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    page_obj = get_paginator(request, posts)
    context = {
        'author': author,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    context = {
        'post': post,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST, files=request.FILES or None)
    if request.method == 'POST' and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user.username)
    template = 'posts/create_post.html'
    context = {
        'form': form,
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(request.POST or None, instance=post)

    if request.user != post.author:
        return redirect('posts:post_detail', post_id)

    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)

    context = {
        'form': form,
        'is_edit': True,
        'post': post,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    # Получите пост и сохраните его в переменную post.
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        # comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %} Новый пост
{% endblock %}
{% block content %}
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
              {% if is_edit %}
                Редактировать пост
              {% else %}
                Новый пост
              {% endif %}
              </div>
              <div class="card-body">
                {% if is_edit %}
                <form method="post" action="{% url 'posts:post_edit' post.id %}">
                {% csrf_token %}
                {% else %}
                <form method="post" action="{% url 'posts:post_create' %}">
                {% csrf_token %}
                {% endif%}
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста
                      <span class="required text-danger" >*</span>
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">
                    </textarea>
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Группа
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      {% for object in form.group %}
                      <option value="{{ object.id }}"> {{ object }} </option>
                      {% endfor%}
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                    {% if is_edit %}
                      Сохранить
                    {% else %}
                      Добавить
                    {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  </body>
</html>
{%endblock%}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
<h1> {{ group.title }} </h1>
{% endblock %}
{% block content %}
<h1>{{ group.title }}</h1>
        <p>
          {{ group.description }}
        </p>
        {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{post.pub_date}}
            </li>
          </ul>
          <p>
            {{ post.text }}
          </p>
        </article>
        {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include 'includes/paginator.html' %}
{% endblock content%}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}
{% endblock %}
{% block content %}
    <h1>Последние обновления на сайте</h1>
    {% for post in page_obj %}
        <ul>
            <li>
                Автор: {{ post.author.get_full_name }}
            </li>
            <li>
                Дата публикации: {{ post.pub_date|date:"d E Y"}}
            </li>
        </ul>
        <p>{{ post.text }}</p>
        {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %}{{ post.text|truncatechars:30 }}{% endblock %}
{% block content %}
{% load thumbnail %}
    <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:'d E Y' }} 
            </li>
          <article>
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
      <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text }}</p>
  <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
</article>
            {% if post.group %} 
            <li class="list-group-item">
              Группа: {{ group.title }}
              {% if post.group %} 
                <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
              {% endif %} 
            </li>
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ author.posts.count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя
              </a>
            </li>
            {% endif %}
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
            {{ post.text|linebreaksbr }} 
          </p>
          {% if user.id == post.author.id %}
             <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
             редактировать запись
          </a>
          {% endif %}
        </article>
      </div> 
    </main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}Профайл пользователя {{ author.get_full_name }} {% endblock %}
{% block content %}
  <h1>Все посты пользователя {{ author.get_full_name }} </h1>
  <h3>Всего постов: {{ author.posts.count }}</h3>   
  {% for post in page_obj %}
  <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>
      {{ post.text }}
    </p>
     <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
  </article>
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}       
       
  {% include 'posts/includes/paginator.html' %}
{% endblock %}